In [1]:
pip install pycoingecko

Collecting pycoingecko
  Downloading pycoingecko-2.2.0-py3-none-any.whl (8.3 kB)
Requirement already satisfied: requests in c:\users\nicho\anaconda3\lib\site-packages (from pycoingecko) (2.24.0)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\nicho\anaconda3\lib\site-packages (from requests->pycoingecko) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in c:\users\nicho\anaconda3\lib\site-packages (from requests->pycoingecko) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\nicho\anaconda3\lib\site-packages (from requests->pycoingecko) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nicho\anaconda3\lib\site-packages (from requests->pycoingecko) (2020.6.20)
Installing collected packages: pycoingecko
Successfully installed pycoingecko-2.2.0
Note: you may need to restart the kernel to use updated packages.

In [46]:
from pycoingecko import CoinGeckoAPI
cg = CoinGeckoAPI()

from datetime import datetime
import pandas as pd
import numpy as np

In [2]:
cg.ping()

{'gecko_says': '(V3) To the Moon!'}

In [16]:
cg.get_price(ids="bitcoin", vs_currencies='usd')

{'bitcoin': {'usd': 49598}}

In [23]:
cg.get_coin_history_by_id('bitcoin','30-12-2017')

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'localization': {'en': 'Bitcoin',
  'de': 'Bitcoin',
  'es': 'Bitcoin',
  'fr': 'Bitcoin',
  'it': 'Bitcoin',
  'pl': 'Bitcoin',
  'ro': 'Bitcoin',
  'hu': 'Bitcoin',
  'nl': 'Bitcoin',
  'pt': 'Bitcoin',
  'sv': 'Bitcoin',
  'vi': 'Bitcoin',
  'tr': 'Bitcoin',
  'ru': 'биткоин',
  'ja': 'ビットコイン',
  'zh': '比特币',
  'zh-tw': '比特幣',
  'ko': '비트코인',
  'ar': 'بيتكوين',
  'th': 'บิตคอยน์',
  'id': 'Bitcoin'},
 'image': {'thumb': 'https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png?1547033579',
  'small': 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png?1547033579'},
 'market_data': {'current_price': {'aed': 50024.57906376443,
   'ars': 253468.12429692186,
   'aud': 17446.3215245937,
   'bch': 5.76928286478153,
   'bdt': 1126110.803183989,
   'bhd': 5132.860612995706,
   'bmd': 13620.3618741461,
   'brl': 45117.7211153463,
   'btc': 1.0,
   'cad': 17128.871750393,
   'chf': 13262.4868659029,
   'clp': 8362902.190725706,
   'cny': 88573.2132675718,
   'czk': 289914.5782287119,
   'dkk': 84525.1736167662,
   'eth': 18.483094024188404,
   'eur': 11345.8976447824,
   'gbp': 10079.0677868681,
   'hkd': 106417.930376984,
   'huf': 3526720.3000726495,
   'idr': 184652192.175199,
   'ils': 47387.96303252911,
   'inr': 869671.001953725,
   'jpy': 1535062.45448282,
   'krw': 14537693.2463698,
   'kwd': 4104.645874754543,
   'lkr': 2087919.548829924,
   'ltc': 60.96840666846534,
   'mmk': 18414729.253845528,
   'mxn': 267888.750532982,
   'myr': 55317.8739192755,
   'ngn': 4884546.501733771,
   'nok': 111755.75019546246,
   'nzd': 19178.1505368914,
   'php': 680527.760679833,
   'pkr': 1505414.7676248574,
   'pln': 47450.61669715,
   'rub': 785377.30638701,
   'sar': 51079.0811004227,
   'sek': 111446.704184538,
   'sgd': 18213.1478981081,
   'thb': 442954.59869004245,
   'try': 51700.07425935065,
   'twd': 404053.46952093,
   'uah': 382908.08925747185,
   'usd': 13620.3618741461,
   'vef': 140859.73944813784,
   'vnd': 309201434.91677517,
   'xag': 804.154745877564,
   'xau': 10.4549897745945,
   'xdr': 9563.95932114975,
   'zar': 168771.061713303,
   'bits': 1000000.0,
   'link': 22041.447552365687,
   'sats': 100000000.0},
  'market_cap': {'aed': 839030999274.6053,
   'ars': 4251262431254.5815,
   'aud': 292616246981.057,
   'bch': 96764575.68919012,
   'bdt': 18887552682553.043,
   'bhd': 86090263023.8938,
   'bmd': 228445816988.881,
   'brl': 756731337692.006,
   'btc': 16772375.0,
   'cad': 287291860324.498,
   'chf': 222443403147.498,
   'clp': 140265731631172.94,
   'cny': 1485583147878.69,
   'czk': 4862556024018.788,
   'dkk': 1417687908840.51,
   'eth': 310005384.13394696,
   'eur': 190297650009.907,
   'gbp': 169049904571.772,
   'hkd': 1784881435006.67,
   'huf': 59151475392930.96,
   'idr': 3097055811734500,
   'ils': 794808686467.7148,
   'inr': 14586448171393.6,
   'jpy': 25746643135006.3,
   'krw': 243831642763082.0,
   'kwd': 68844659853.58617,
   'lkr': 35019369642806.27,
   'ltc': 1022584979.7960014,
   'mmk': 308858744568967.1,
   'mxn': 4493130582220.62,
   'myr': 927812125576.808,
   'ngn': 81925445632016.88,
   'nok': 1874409350684.6182,
   'nzd': 321663132611.194,
   'php': 11414066800032.4,
   'pkr': 25249381013141.95,
   'pln': 795859537225.861,
   'rub': 13172642699212.8,
   'sar': 856717502871.7015,
   'sek': 1869225915097.14,
   'sgd': 305477746477.531,
   'thb': 7429400637203.895,
   'try': 867133033005.6757,
   'twd': 6776936310856.11,
   'uah': 6422278063559.784,
   'usd': 228445816988.881,
   'vef': 2362552372426.4595,
   'vnd': 5186042416962243,
   'xag': 13487584955.8882,
   'xau': 175355009.120664,
   'xdr': 160410312219.069,
   'zar': 2830691536203.66,
   'bits': 16772375000000.0,
   'link': 369687423891.10944,
   'sats': 1677237500000000},
  'total_volume': {'aed': 13223772038.888288,
   'ars': 67003156399.47071,
   'aud': 4611856472.88116,
   'bch': 1525083.9259334763,
   'bdt': 297682315984.16693,
   'bhd': 1356848571.721612,
   'bmd': 3600481281.03768,
   'brl': 11926666253.0629,
   'btc': 264345.493482963,
   'cad': 4527940055.66402,
   'chf': 3505878635.37842,
   'clp': 2210695506557.1357,
   'cny': 23413929770.588,
   'czk': 76637612249.77382,
   'dkk': 22343848731.4572,
   'eth': 4885922.610916088,
   'eur': 2999236911.91719,
   'gbp': 2664356147.96788,
   'hkd': 28131100320.9394,
   'huf': 932272618099.0865,
   'idr': 48811974863263.9,
   'ils': 12526794472.986298,
   'inr': 229893610179.28,
   'jpy': 405786842057.429,
   'krw': 3842973695315.56,
   'kwd': 1085044639.3347962,
   'lkr': 551932123488.1709,
   'ltc': 16116723.547645444,
   'mmk': 4867850691962.943,
   'mxn': 70815183958.1755,
   'myr': 14623030679.6192,
   'ngn': 1291207855441.2922,
   'nok': 29542128934.978218,
   'nzd': 5069657667.76511,
   'php': 179894446725.766,
   'pkr': 397949609644.3324,
   'pln': 12543356686.879,
   'rub': 207610951627.194,
   'sar': 13502524900.147509,
   'sek': 29460434014.7115,
   'sgd': 4814563569.00357,
   'thb': 117093051981.26692,
   'try': 13666681643.19386,
   'twd': 106809713794.014,
   'uah': 101220027813.38469,
   'usd': 3600481281.03768,
   'vef': 37235637336.29954,
   'vnd': 81736005898715.08,
   'xag': 212574683.135671,
   'xau': 2763729.43132451,
   'xdr': 2528189546.40031,
   'zar': 44613869594.2467,
   'bits': 264345493482.963,
   'link': 5826557330.308955,
   'sats': 26434549348296.3}},
 'community_data': {'facebook_likes': None,
  'twitter_followers': 603664,
  'reddit_average_posts_48h': 2.042,
  'reddit_average_comments_48h': 445.896,
  'reddit_subscribers': 612412,
  'reddit_accounts_active_48h': '14074.0'},
 'developer_data': {'forks': 13660,
  'stars': 23665,
  'subscribers': 2513,
  'total_issues': 3591,
  'closed_issues': 3022,
  'pull_requests_merged': 5038,
  'pull_request_contributors': 450,
  'code_additions_deletions_4_weeks': {'additions': None, 'deletions': None},
  'commit_count_4_weeks': 147},
 'public_interest_stats': {'alexa_rank': 2912, 'bing_matches': None}}

In [28]:
cg.get_coin_history_by_id('bitcoin','01-01-1990, 01-01-2020')

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'localization': {'en': 'Bitcoin',
  'de': 'Bitcoin',
  'es': 'Bitcoin',
  'fr': 'Bitcoin',
  'it': 'Bitcoin',
  'pl': 'Bitcoin',
  'ro': 'Bitcoin',
  'hu': 'Bitcoin',
  'nl': 'Bitcoin',
  'pt': 'Bitcoin',
  'sv': 'Bitcoin',
  'vi': 'Bitcoin',
  'tr': 'Bitcoin',
  'ru': 'биткоин',
  'ja': 'ビットコイン',
  'zh': '比特币',
  'zh-tw': '比特幣',
  'ko': '비트코인',
  'ar': 'بيتكوين',
  'th': 'บิตคอยน์',
  'id': 'Bitcoin'},
 'image': {'thumb': 'https://assets.coingecko.com/coins/images/1/thumb/bitcoin.png?1547033579',
  'small': 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png?1547033579'}}

In [52]:
btc_df = pd.DataFrame(cg.get_coin_market_chart_by_id('bitcoin',vs_currency='usd',days = 6000,))

In [56]:
btc_df.head()

,prices,market_caps,total_volumes
0,"[1367107200000, 135.3]","[1367107200000, 1500517590]","[1367107200000, 0]"
1,"[1367193600000, 141.96]","[1367193600000, 1575032004.0]","[1367193600000, 0.0]"
2,"[1367280000000, 135.3]","[1367280000000, 1501657493.0]","[1367280000000, 0.0]"
3,"[1367366400000, 117.0]","[1367366400000, 1298951550.0]","[1367366400000, 0.0]"
4,"[1367452800000, 103.43]","[1367452800000, 1148667722.0]","[1367452800000, 0.0]"

In [61]:
btc_df.to_csv("test_btc_df.csv", encoding='utf-8', index=False)

In [63]:
btc_df.head()

,prices,market_caps,total_volumes,Time
0,"[1367107200000, 135.3]","[1367107200000, 1500517590]","[1367107200000, 0]",
1,"[1367193600000, 141.96]","[1367193600000, 1575032004.0]","[1367193600000, 0.0]",
2,"[1367280000000, 135.3]","[1367280000000, 1501657493.0]","[1367280000000, 0.0]",
3,"[1367366400000, 117.0]","[1367366400000, 1298951550.0]","[1367366400000, 0.0]",
4,"[1367452800000, 103.43]","[1367452800000, 1148667722.0]","[1367452800000, 0.0]",

In [72]:
btc_df_cleaned = pd.DataFrame(btc_df)

In [74]:
btc_df_cleaned[["prices","times"]] = pd.DataFrame(btc_df_cleaned.prices.tolist(),index= btc_df_cleaned.index)

In [75]:
btc_df_cleaned.head()

,prices,market_caps,total_volumes,Time,times
0,1367107200000,"[1367107200000, 1500517590]","[1367107200000, 0]",,135.30
1,1367193600000,"[1367193600000, 1575032004.0]","[1367193600000, 0.0]",,141.96
2,1367280000000,"[1367280000000, 1501657493.0]","[1367280000000, 0.0]",,135.30
3,1367366400000,"[1367366400000, 1298951550.0]","[1367366400000, 0.0]",,117.00
4,1367452800000,"[1367452800000, 1148667722.0]","[1367452800000, 0.0]",,103.43